apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-bqlt
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0045-tenant/tkrw-pr712-0075-0045-app/devfile-sample-bqlt@sha256:96e69f5fba42d6677492d6ac0bff5852bfed0beca0f3ef60264579491248f81f
        name: my-nodejs
        resources: {}
status: {}
